### ISSUE TITLE
support password encryption via maven

### ISSUE THREAD

**Issue by krasv** [kiwigrid/antora-maven-content-extension#93]
Maven supports password encryption (https://maven.apache.org/guides/mini/guide-encryption.html). That is done via an additional configuration (settings-security.xml).

The extension allows/considers as of now only plain passwords via the settings.xml. 

Expectation: password encryption is supported to use shared developer environments.

**Comment by jekkel** [comment]
With #130 being available since [v1.6.0](https://github.com/kiwigrid/antora-maven-content-extension/releases/tag/v1.6.0) there's now a CI/CD compatible way of providing credentials without storing them as plain text in a settings file. The password encryption feature of maven is too proprietary to be re-implemented in nodejs. If anyone want's to contribute, feel free to raise a PR and reopen this issue.
